project:
  type: website

website:
  site-url: https://qiufei.site/web-slide
  search: false
  # 设置网站图标
  favicon: profile.jpg
  # title: "课件"
  navbar:
    left:
      - text: "首页"
        href: https://qiufei.site
    right:
      - text: R课件
        href: https://qiufei.site/web-slide-r
      # - text: python课件
      #   href: https://qiufei.site/web-slide-python
      # - text: supermind课件
      #   href: https://qiufei.site/web-slide-supermind
      # - text: izhi课件
      #   href: https://qiufei.site/web-slide-izhi
      - text: 营销课件
        href: https://qiufei.site/web-slide-marketing
      # - icon: github
      #   href: https://github.com/
      - about.qmd

metadata-files:
  - https://github.com/qiufei/qiufei.github.io/blob/main/page-footer.yml

format:
  html:
    theme:
     light: journal
     dark: cyborg
    css: styles.css

execute:
  freeze: auto



